# ====================================================================================
# ROLE : CONFIGURATION DE PRODUCTION DE LA BASE DE DONNÉES CLOUD
# RESPONSIBILITY : Connecte Spring Boot à PostgreSQL sur Neon.tech de manière sécurisée.
# ARCHITECTURE : Utilise des variables d'environnement pour masquer les mots de passe.
# ====================================================================================
spring:
  datasource:
    # Si la variable ${DB_URL} n'existe pas (ex: en local), Spring bascule sur ta BDD locale par défaut
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gescom_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # 'update' permet à Hibernate de créer automatiquement tes tables (products, clients) sur Neon lors du premier démarrage
      ddl-auto: update
    show-sql: false # Désactivé en production pour ne pas surcharger les logs du cloud
    properties:
      hibernate:
        format_sql: true
        # Optimisation majeure : Neon exige une connexion sécurisée chiffrée SSL
        ssl: true
        sslmode: require
